// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHieW7Ab3V6OATVZD0oy_mE9qJariiPTw',
    appId: '1:212422150927:web:1b34f808bab44606db8c7a',
    messagingSenderId: '212422150927',
    projectId: 'car-store-c22d4',
    authDomain: 'car-store-c22d4.firebaseapp.com',
    storageBucket: 'car-store-c22d4.appspot.com',
    measurementId: 'G-D8J1YNFH5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfPTBaKuf45XqZbl5Gj_-RrERL-goJAbs',
    appId: '1:212422150927:android:1ffeba7c1de2935ddb8c7a',
    messagingSenderId: '212422150927',
    projectId: 'car-store-c22d4',
    storageBucket: 'car-store-c22d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOjRENvYEngGyWiE_bKKOSaZEnrq9cpYo',
    appId: '1:212422150927:ios:7243de90cba963c9db8c7a',
    messagingSenderId: '212422150927',
    projectId: 'car-store-c22d4',
    storageBucket: 'car-store-c22d4.appspot.com',
    iosBundleId: 'com.example.carStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOjRENvYEngGyWiE_bKKOSaZEnrq9cpYo',
    appId: '1:212422150927:ios:7243de90cba963c9db8c7a',
    messagingSenderId: '212422150927',
    projectId: 'car-store-c22d4',
    storageBucket: 'car-store-c22d4.appspot.com',
    iosBundleId: 'com.example.carStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHieW7Ab3V6OATVZD0oy_mE9qJariiPTw',
    appId: '1:212422150927:web:8d2bf7e0fe10d96bdb8c7a',
    messagingSenderId: '212422150927',
    projectId: 'car-store-c22d4',
    authDomain: 'car-store-c22d4.firebaseapp.com',
    storageBucket: 'car-store-c22d4.appspot.com',
    measurementId: 'G-V4XCLKB1Z7',
  );
}
